### ISSUE TITLE
Saving more than 5 tattoos?

### ISSUE THREAD

**Issue by TobiasThaisen** [ESX-PUBLIC/esx_tattooshop#4]
Can't save more than 5 tattoos beacuse of the VARCHAR limit to 250 letters. Anybody know a fix to this? Setting it to LONGTEXT will just give more problems in the console

**Comment by HawaiiBeach** [comment]
Why wouldn't `LONGTEXT ` work?

**Comment by TobiasThaisen** [comment]
Beacuse on LONGTEXT you can't set DEFAULT '{}'

**Comment by HawaiiBeach** [comment]
You don't really need the default thing

**Comment by TobiasThaisen** [comment]
If the default ain't there it's gonna throw alot of errors in the serversided console

**Comment by HawaiiBeach** [comment]
Duplicate of #3
