### ISSUE TITLE
You cannot compare a nil with a string.

### ISSUE THREAD

**Issue by Helweg** [ESX-PUBLIC/esx_tattooshop#6]
Since you are using a longtext in the sql, then you cannot set a default value. This means, if there is no data stored on the player in the database, then the tattoos value in the database will be nil.
You cannot compare a nil value with a string as i assume you are trying to do here:

https://github.com/ESX-PUBLIC/esx_tattooshop/blob/9897879a4c22977c3a24898837f5a43866904cb7/server/main.lua#L12

furthermore, since you want to verify the data from the tattoos column, then you should be checking result[1].tattoos and not result[1] as you are doing at:

https://github.com/ESX-PUBLIC/esx_tattooshop/blob/9897879a4c22977c3a24898837f5a43866904cb7/server/main.lua#L12

Your code should instead be something like this:

```
ESX.RegisterServerCallback('esx_tattooshop:requestPlayerTattoos', function(source, cb)
  local xPlayer = ESX.GetPlayerFromId(source)

  MySQL.Async.fetchAll('SELECT tattoos FROM users WHERE identifier = @identifier', {
      ['@identifier'] = xPlayer.identifier
    }, function(result)
      if result[1] ~= nil then
        if result[1].tattoos ~= nil then
          if result[1].tattoos ~= "" then
            cb(json.decode(result[1].tattoos))
          else
            cb({})
          end
        else
          cb({})
        end
      else
        cb({})
      end
  end)
end)
```

You should really start to look at what you are doing in your code before pushing it.

**Comment by HawaiiBeach** [comment]
oh god that code, but hey it's fixed now - update the resource!
